### ISSUE TITLE
Add authentication

### ISSUE THREAD

**Issue by sirchras** [sirchras/bookish-train#23]
- [x] create auth components - #25 
- [x] create auth routes - #26 
- [x] create user db queries - #27 
- [x] create sign-in and register form components - #4 
- [ ] update other components to use auth
